apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patches/add-unified-service-labels.yaml
    target:
      group: apps
      kind: Deployment
      version: v1
  - path: patches/add-unified-service-environment-variables.yaml
    target:
      group: apps
      kind: Deployment
      version: v1

replacements:
  - path: replacements/update-service-environment.yaml
  - path: replacements/update-service-name.yaml
  - path: replacements/update-service-version.yaml